# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        none

# Site settings
title: Airline
email: rvesse@dotnetrdf.org
description: > 
  Annotation-driven Java framework for building powerful Git style CLIs in Java
baseurl: "/airline" 
url: "http://rvesse.github.io"
twitter_username: RobVesse
github_username:  rvesse
exclude: [ "scripts", "pom.xml", "assembly.xml", "target" ]

author:
  name:           "Rob Vesse"
  url:            https://twitter.com/RobVesse

# Custom vars
version:          2.9.0
dev_version:	"2.10.0-SNAPSHOT"

github:
  repo:           https://github.com/rvesse/airline
  
javadoc_versions: [ "2.8.5", "2.8.4", "2.8.3", "2.8.2", "2.8.1", "2.8.0", "2.7.2", "2.7.1", "2.7.0", "2.6.0", "2.5.0", "2.4.0", "2.3.0", "2.2.0", "2.1.0" ]
