name: Build

on:
  push:
    branches: [ main, 3x ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build - JDK ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ "8", "11", "17" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -e -Prelease -Dgpg.skip=true clean install
    - name: Run ITs and coverage
      if: matrix.java == '11'
      run: mvn -B -e verify -Dcoveralls.token=${{ secrets.COVERALLS_TOKEN }} -Pcoveralls
